# Site Settings
title: Xiao Li
email: xli87@bu.edu
description: A guide to getting started with Jekyll.
baseurl: ""
url: "http://xli4217.github.io"
#twitter_username: taniarascia
#github_username:  taniarascia
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages', 'assets']
kramdown:
  input: GFM
cover: "/assets/images/test.jpg"
