# Site Settings
title: Xiao Li
email: xli87@bu.edu
description: >
  A guide to getting started with Jekyll.
baseurl: ""
url: "http://localhost:4000"
#twitter_username: taniarascia
#github_username:  taniarascia
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
